packages:
  - apps/*
  - packages/*

allowBuilds:
  "@prisma/client": false
  better-sqlite3: false
  unrs-resolver: true

minimumReleaseAgeExclude:
  - "@aws-sdk/client-s3@3.1122.0"
  - shadcn@4.19.1
